### ISSUE TITLE
SwarmTest.CanBroadcastWhlieMining test fails with IOException on Windows

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#148]
See also <https://travis-ci.com/dahlia/libplanet/jobs/187118894#L2315-L2322>.

        System.IO.IOException : The process cannot access the file 'index' because it is being used by another process.
        Stack Trace:
             at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
             at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
             at Libplanet.Tests.Store.FileStoreFixture.Dispose()
             at Libplanet.Tests.Net.SwarmTest.Dispose()
             at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)

**Comment by dahlia** [comment]
Another build: <https://travis-ci.com/planetarium/libplanet/jobs/187184154#L2891-L2897>.
