### ISSUE TITLE
Configurable SHA1 Provider

### ISSUE THREAD

**Issue by moreal** [planetarium/libplanet#2368]
While working for `lib9c-wasm`, an experimental project to provider Lib9c as WASM library, I saw that [.NET WASM doesn't support `SHA1CryptoServiceProvider`](https://learn.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/cryptography-apis-not-supported-on-blazor-webassembly). It was when using `Libplanet.Assets.Currency` because it uses `SHA1CryptoServiceProvider` to calculate the currency's hash. Since there is `SHA1` abstract class and there are two implmenetations [`SHA1CryptoServiceProvider`](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.sha1cryptoserviceprovider?view=net-6.0), [`SHA1Managed`](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.sha1managed?view=net-6.0), it seems able to be configurable.

I guess this project isn't aimed at supporting WASM, but I've written an issue to inform and suggest that there are such cases.

**Comment by dahlia** [comment]
I wonder what happens if `SHA1CryptoServiceProvider` is tried to be used on WASM.  Does it throw an exception during instantiating?  Or the compiler disallows to use `SHA1CryptoServiceProvider`?

If it's a runtime error we could make `Currency` to automatically fall back to `SHA1Managed` when it's failed to instantiate `SHA1CryptoServiceProvider`.

**Comment by moreal** [comment]
It was a runtime error so it seems able to be resolved as you said.

```
webpack://dotnet/./native/dotnet.js:4704
                    var err = new Error(msg);
                              ^
Error: System.Reflection.TargetInvocationException: Arg_TargetInvocationException
 ---> System.PlatformNotSupportedException: SystemSecurityCryptographyCsp_PlatformNotSupported
   at System.Security.Cryptography.SHA1CryptoServiceProvider..ctor()
   at Libplanet.Assets.Currency.GetHash()
   at Libplanet.Assets.Currency..ctor(String ticker, Byte decimalPlaces, IImmutableSet`1 minters)
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object , Object[] , Boolean )
   Exception_EndOfInnerExceptionStack
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object , Object[] , Boolean )
   at System.Reflection.RuntimeConstructorInfo.DoInvoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags , Binder , Object[] , CultureInfo )
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at Lib9c.Wasm.JsonUtils.ConvertJsonElementTo(JsonElement element, Type targetType)
   at Lib9c.Wasm.JsonUtils.<>c__DisplayClass1_0.<ConvertJsonElementTo>b__0(ParameterInfo parameter)
   at System.Linq.Enumerable.SelectArrayIterator`2[[System.Reflection.ParameterInfo, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1[[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].AddRange(IEnumerable`1 )
   at System.Collections.Generic.EnumerableHelpers.ToArray[Object](IEnumerable`1 )
   at System.Linq.Enumerable.ToArray[Object](IEnumerable`1 )
   at Lib9c.Wasm.JsonUtils.ConvertJsonElementTo(JsonElement element, Type targetType)
   at Lib9c.Wasm.JsonUtils.<>c__DisplayClass1_0.<ConvertJsonElementTo>b__0(ParameterInfo parameter)
   at System.Linq.Enumerable.SelectArrayIterator`2[[System.Reflection.ParameterInfo, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1[[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].AddRange(IEnumerable`1 )
   at System.Collections.Generic.EnumerableHelpers.ToArray[Object](IEnumerable`1 )
   at System.Linq.Enumerable.ToArray[Object](IEnumerable`1 )
   at Lib9c.Wasm.JsonUtils.ConvertJsonElementTo(JsonElement element, Type targetType)
   at Lib9c.Wasm.Program.BuildAction(String actionTypeString, JsonElement dictionary)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
--- End of stack trace from previous location ---
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.Invoke(JSRuntime jsRuntime, DotNetInvocationInfo& invocationInfo, String argsJson)
   at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.InvokeDotNet(String assemblyName, String methodIdentifier, String dotNetObjectId, String argsJson)
    at Object._convert_exception_for_method_call (webpack://dotnet/./native/dotnet.js:4704:31)
    at Object._handle_exception_for_call (webpack://dotnet/./native/dotnet.js:4737:36)
    at invokeDotNet (https://mono-wasm.invalid/managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_InvokeDotNet:20:21)
    at Object.invokeDotNetFromJS (webpack://dotnet/./src/interop.ts:102:12)
    at invokePossibleInstanceMethod (webpack://dotnet/./src/dotnet-js-interop.ts:228:43)
    at fn (webpack://dotnet/./src/dotnet-js-interop.ts:116:16)
    at Object.invoke (webpack://dotnet/./src/interop.ts:33:16)
```
