### ISSUE TITLE
`StoreLoaderAttribute.ListStoreLoaderMethods()` does not find RocksDBStore

### ISSUE THREAD

**Issue by tkiapril** [planetarium/libplanet#2623]
On planet cli:
```
$ planet store block-by-index rocksdb+file:///*DIR*/9c-main-snapshot  0
Unhandled Exception: System.ArgumentException: The store URI scheme rocksdb+file:// is not supported.  See also the list of supported store URI schemes:

  URI SCHEME     PROVIDED BY
  default+file:  DefaultStore
  memory:        MemoryStore
 (Parameter 'uriString')
   at Libplanet.Extensions.Cocona.Utils.LoadStoreFromUri(String uriString) in /home/runner/work/libplanet/libplanet/Libplanet.Extensions.Cocona/Utils.cs:line 128
   at Libplanet.Extensions.Cocona.Commands.StoreCommand.BlockByIndex(String home, Int32 blockIndex) in /home/runner/work/libplanet/libplanet/Libplanet.Extensions.Cocona/Commands/StoreCommand.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at Cocona.Command.Dispatcher.Middlewares.CoconaCommandInvokeMiddleware.DispatchAsync(CommandDispatchContext ctx)
   at Cocona.Command.Dispatcher.Middlewares.HandleParameterBindExceptionMiddleware.DispatchAsync(CommandDispatchContext ctx)
   at Cocona.Command.Dispatcher.Middlewares.HandleExceptionAndExitMiddleware.DispatchAsync(CommandDispatchContext ctx)
```
Also, this happens when used on other projects as well (NineChronicles.Headless.Executable.)

**Comment by dahlia** [comment]
Might be relevant: <https://github.com/planetarium/Telescope/blob/00c04c9d164bd12021cc19e3d3b72e1ff170708e/Program.cs#L47-L51>.
