### ISSUE TITLE
Fix `SwarmBenchmark`

### ISSUE THREAD

**Issue by greymistcube** [planetarium/libplanet#2675]
Not even sure since when this has been broken, but all benchmarks fail to run properly on all operating systems. 🙄

```
2022-12-26T15:21:12.1532218Z // **************************
2022-12-26T15:21:12.1533025Z // Benchmark: SwarmBenchmark.BroadcastBlock: Job-LGMTQP(InvocationCount=1, UnrollFactor=1)
2022-12-26T15:21:12.1533554Z // *** Execute ***
2022-12-26T15:21:12.1533899Z // Launch: 1 / 1
2022-12-26T15:21:12.1535438Z // Execute: dotnet "b78e72a8-4d5f-4585-93aa-f4d6733854f2.dll" --benchmarkName "Libplanet.Benchmarks.SwarmBenchmark.BroadcastBlock" --job "InvocationCount=1, UnrollFactor=1" --benchmarkId 0 in D:\a\libplanet\libplanet\Libplanet.Benchmarks\bin\Release\net6.0\b78e72a8-4d5f-4585-93aa-f4d6733854f2\bin\Release\netcoreapp6.0
2022-12-26T15:21:12.2326400Z // BeforeAnythingElse
2022-12-26T15:21:12.5534833Z 
2022-12-26T15:21:12.5716756Z // Benchmark Process Environment Information:
2022-12-26T15:21:12.5723749Z // Runtime=.NET Core 6.0.12 (CoreCLR 6.0.1222.56807, CoreFX 6.0.1222.56807), X64 RyuJIT
2022-12-26T15:21:12.5724634Z // GC=Concurrent Workstation
2022-12-26T15:21:12.5951986Z // Job: Job-VVUBVX(InvocationCount=1, UnrollFactor=1)
2022-12-26T15:21:12.5952522Z 
2022-12-26T15:21:12.6177014Z OverheadJitting  1: 1 op, 272300.00 ns, 272.3000 us/op
2022-12-26T15:21:12.9987084Z 
2022-12-26T15:21:13.2326191Z System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
2022-12-26T15:21:13.2328563Z  ---> Libplanet.Blocks.InvalidBlockStateRootHashException: Block #0 538322c25e713ca2c1b54549123419f2d34e74b8028e438f7c074f3bd6b193a4's state root hash is 0000000000000000000000000000000000000000000000000000000000000000, but the execution result is 1b16b1df538ba12dc3f97edbb85caa7050d46c148134290feba80f8236c83db9.
2022-12-26T15:21:13.2330014Z    at Libplanet.Blockchain.BlockChain`1.ExecuteActions(Block`1 block, Nullable`1 stateCompleters) in D:\a\libplanet\libplanet\Libplanet\Blockchain\BlockChain.cs:line 912
2022-12-26T15:21:13.2331181Z    at Libplanet.Blockchain.BlockChain`1.Append(Block`1 block, Boolean evaluateActions, Boolean renderBlocks, Boolean renderActions, IReadOnlyList`1 actionEvaluations, Nullable`1 stateCompleters) in D:\a\libplanet\libplanet\Libplanet\Blockchain\BlockChain.cs:line 1203
2022-12-26T15:21:13.2332997Z    at Libplanet.Blockchain.BlockChain`1..ctor(IBlockPolicy`1 policy, IStagePolicy`1 stagePolicy, IStore store, IStateStore stateStore, Guid id, Block`1 genesisBlock, Boolean inFork, IEnumerable`1 renderers, IBlockChainStates`1 blockChainStates, ActionEvaluator`1 actionEvaluator) in D:\a\libplanet\libplanet\Libplanet\Blockchain\BlockChain.cs:line 262
2022-12-26T15:21:13.2336390Z    at Libplanet.Benchmarks.SwarmBenchmark.InitializeSwarms() in D:\a\libplanet\libplanet\Libplanet.Benchmarks\SwarmBenchmark.cs:line 56
2022-12-26T15:21:13.2337227Z    at BenchmarkDotNet.Engines.Engine.RunIteration(IterationData data)
2022-12-26T15:21:13.2337966Z    at BenchmarkDotNet.Engines.EngineFactory.Jit(Engine engine, Int32 jitIndex, Int32 invokeCount, Int32 unrollFactor)
2022-12-26T15:21:13.2338763Z    at BenchmarkDotNet.Engines.EngineFactory.CreateReadyToRun(EngineParameters engineParameters)
2022-12-26T15:21:13.2340195Z    at BenchmarkDotNet.Autogenerated.Runnable_0.Run(IHost host, String benchmarkName) in D:\a\libplanet\libplanet\Libplanet.Benchmarks\bin\Release\net6.0\b78e72a8-4d5f-4585-93aa-f4d6733854f2\b78e72a8-4d5f-4585-93aa-f4d6733854f2.notcs:line 164
2022-12-26T15:21:13.2341114Z    --- End of inner exception stack trace ---
2022-12-26T15:21:13.2341986Z    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
2022-12-26T15:21:13.2342887Z    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2022-12-26T15:21:13.2343632Z    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
2022-12-26T15:21:13.2344978Z    at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in D:\a\libplanet\libplanet\Libplanet.Benchmarks\bin\Release\net6.0\b78e72a8-4d5f-4585-93aa-f4d6733854f2\b78e72a8-4d5f-4585-93aa-f4d6733854f2.notcs:line 47
2022-12-26T15:21:13.2345875Z // AfterAll
2022-12-26T15:21:13.2442728Z ExitCode != 0
2022-12-26T15:21:13.2443665Z // Benchmark Process 908 has exited with code -1
2022-12-26T15:21:13.2444389Z No more Benchmark runs will be launched as NO measurements were obtained from the previous run!
```

**Comment by greymistcube** [comment]
Solved by removing the test. 🙄
