### ISSUE TITLE
TxStagedNotToBroadcast test sometimes broken

### ISSUE THREAD

**Issue by earlbread** [planetarium/libplanet#328]
```
Failed   Libplanet.Tests.Net.SwarmTest.TxStagedNotToBroadcast
Error Message:
 System.IO.IOException : The process cannot access the file '6212b605aaf4297ca8a4a0adbcdeecc996bbefed503814134da83758dda93b80' because it is being used by another process.
Stack Trace:
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Libplanet.Tests.Store.FileStoreFixture.Dispose() in D:\a\1\s\Libplanet.Tests\Store\FileStoreFixture.cs:line 23
   at Libplanet.Tests.Net.SwarmTest.Dispose() in D:\a\1\s\Libplanet.Tests\Net\SwarmTest.cs:line 85
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 79
Standard Output Messages:
 09:08:10[@0567ACaf7E6d6905EdaBB429879276bfd0f91b11][14] - An unexpected exception occured during BroadcastTxAsync()
```

**Comment by earlbread** [comment]
```
[xUnit.net 00:01:48.19]     Libplanet.Tests.Net.SwarmTest.TxStagedNotToBroadcast [FAIL]
Failed   Libplanet.Tests.Net.SwarmTest.TxStagedNotToBroadcast
Error Message:
 System.IO.IOException : The process cannot access the file 'C:\Users\VssAdministrator\AppData\Local\Temp\filestore_test_3b188c66-2197-4204-ac71-1389564487eb\tx\50fb\af39a8336ae5e79c894b367031334192be4e639dde9cd1cd60aebc3bc1bb' because it is being used by another process.
Stack Trace:
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileInfo.OpenRead()
   at Libplanet.Store.FileStore.GetTransaction[T](TxId txid) in D:\a\1\s\Libplanet\Store\FileStore.cs:line 372
   at Libplanet.Store.TransactionSet`1.get_Item(TxId key) in D:\a\1\s\Libplanet\Store\TransactionSet.cs:line 38
   at Libplanet.Tests.Net.SwarmTest.TxStagedNotToBroadcast() in D:\a\1\s\Libplanet.Tests\Net\SwarmTest.cs:line 663
   at Libplanet.Tests.Net.SwarmTest.TxStagedNotToBroadcast() in D:\a\1\s\Libplanet.Tests\Net\SwarmTest.cs:line 668
```

**Comment by dahlia** [comment]
This test was removed at all by the patch #470.
