### ISSUE TITLE
System.IO.IOException: Unable to read data from the transport connection

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet#404]
```
System.IO.IOException: Unable to read data from the transport connection: 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다.

. ---> System.Net.Sockets.SocketException: 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다.



  at System.Net.Sockets.Socket.EndReceive (System.IAsyncResult asyncResult) [0x00012] in <c9226b2f33b7421e85bb391f94075e49>:0 

  at System.Net.Sockets.NetworkStream.EndRead (System.IAsyncResult asyncResult) [0x00057] in <c9226b2f33b7421e85bb391f94075e49>:0 

   --- End of inner exception stack trace ---

  at System.Net.Sockets.NetworkStream.EndRead (System.IAsyncResult asyncResult) [0x0009b] in <c9226b2f33b7421e85bb391f94075e49>:0 

  at System.IO.Stream+<>c.<BeginEndReadAsync>b__43_1 (System.IO.Stream stream, System.IAsyncResult asyncResult) [0x00000] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 

  at System.Threading.Tasks.TaskFactory`1+FromAsyncTrimPromise`1[TResult,TInstance].Complete (TInstance thisRef, System.Func`3[T1,T2,TResult] endMethod, System.IAsyncResult asyncResult, System.Boolean requiresSynchronization) [0x00000] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 

--- End of stack trace from previous location where exception was thrown ---

  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 

  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 

  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 

  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 

  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 

  at Libplanet.Stun.Messages.StunMessage+<Parse>d__20.MoveNext () [0x00083] in <16283acc32284612a6c17ae223c508e1>:0 

--- End of stack trace from previous location where exception was thrown ---

  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 

  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 

  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 

  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 

  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 

  at Libplanet.Stun.TurnClient+<AcceptRelayedStreamAsync>d__27.MoveNext () [0x001e5] in <16283acc32284612a6c17ae223c508e1>:0 

--- End of stack trace from previous location where exception was thrown ---

  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 

  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 

  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 

  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 

  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 

  at Libplanet.Net.Swarm`1+<BindingProxies>d__84[T].MoveNext () [0x00092] in <e16ca518ab934a82bde650ed7164c828>:0 
```

**Comment by longfin** [comment]
it seemed causes to #871 .

**Comment by earlbread** [comment]
This log also seems relevant.
```
[12:25:20 DBG] Branch point is #463 dd1b9f31e3e60106ab087844f724bee4a814d5febeaeab5eda3c32b6f7751387.
[12:25:20 DBG] It doesn't need to fork.
[12:25:20 DBG] Trying to fill up previous blocks...
[12:25:20 DBG] Required hashes (count: 1). (tip: dd1b9f31e3e60106ab087844f724bee4a814d5febeaeab5eda3c32b6f7751387)
[12:25:20 INF] Try to download blocks from Unspecified/localhost:59876@00ad5D7cCF838a61c2c075E5834B22AC09De9F1d...
[12:25:21 DBG] Request taken. 0 requests are left.
[12:25:21 DBG] Trying to send Libplanet.Net.Messages.GetBlocks to 0x00ad5D7cCF838a61c2c075E5834B22AC09De9F1d...
[12:25:21 DBG] A message Libplanet.Net.Messages.GetBlocks sent.
[12:25:37 INF] Cancellation requested; shut down NetMQTransport.ProcessRuntime()...
[12:26:05 DBG] A message has parsed: Libplanet.Net.Messages.BlockHeaderMessage, from 0x00ad5D7cCF838a61c2c075E5834B22AC09De9F1d
[12:26:05 DBG] Block header of hash [39cef6a7121391c18dfc34a66399c04f86b0916afaf3771301ee02a98d3a541b] (index: 467) received.
[12:26:08 DBG] A message has parsed: Libplanet.Net.Messages.BlockHeaderMessage, from 0x00ad5D7cCF838a61c2c075E5834B22AC09De9F1d
[12:26:08 DBG] Block header of hash [b31dea6fec392587ce85dd16bcdff4890fe2b8ea1c082156f1cba2409788b143] (index: 468) received.
[12:26:11 DBG] A message has parsed: Libplanet.Net.Messages.BlockHeaderMessage, from 0x00ad5D7cCF838a61c2c075E5834B22AC09De9F1d
[12:26:11 DBG] Block header of hash [6ac29f76fbfc212868e83902c927901c80bfb825ae235f38e6129d7d6845dbd7] (index: 469) received.
[12:26:14 DBG] A message has parsed: Libplanet.Net.Messages.BlockHeaderMessage, from 0x00ad5D7cCF838a61c2c075E5834B22AC09De9F1d
[12:26:14 DBG] Block header of hash [07afb876083cd791003ee85e22ca8322b2e6a380e9c8db29fe366609e006edc9] (index: 470) received.
[12:26:17 DBG] A message has parsed: Libplanet.Net.Messages.BlockHeaderMessage, from 0x00ad5D7cCF838a61c2c075E5834B22AC09De9F1d
...
[12:31:46 DBG] Block header of hash [2b43c64243875c06acb84a7557db36643e32339d15623743e5356fb9b3f01c1f] (index: 580) received.
[12:32:28 DBG] Rebuilding connection...
[12:32:28 DBG] FindPeerAsync() with 0x836c3D199A87d3B2D58A0e8EB8D26c49366C0B7e to null. (depth: -1)
[12:32:28 DBG] FindPeerAsync() with 0x1b26a3e1E61324Ed22bf31c9b9bf18e908bc72ab to null. (depth: -1)
[12:32:28 DBG] FindPeerAsync() with 0x3D3c0F3c786DE7A9BA2AAF9f1CE3365dc95c3287 to null. (depth: -1)
[12:32:28 DBG] FindPeerAsync() with 0x3D92c7980da6dD47E0874C2D04D9aa2BC526433B to null. (depth: -1)
[12:33:03 ERR] An unexpected exception occurred during ProcessMessage(): System.IO.IOException: Unable to read data from the transport connection: Operation timed out.
 ---> System.Net.Sockets.SocketException (60): Operation timed out
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at Libplanet.Stun.Messages.StunMessage.Parse(Stream stream) in /Users/earl/planetarium/libplanet/Libplanet.Stun/Stun/Messages/StunMessage.cs:line 89
   at Libplanet.Stun.TurnClient.ProcessMessage() in /Users/earl/planetarium/libplanet/Libplanet.Stun/Stun/TurnClient.cs:line 269
System.IO.IOException: Unable to read data from the transport connection: Operation timed out.
 ---> System.Net.Sockets.SocketException (60): Operation timed out
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at Libplanet.Stun.Messages.StunMessage.Parse(Stream stream) in /Users/earl/planetarium/libplanet/Libplanet.Stun/Stun/Messages/StunMessage.cs:line 89
   at Libplanet.Stun.TurnClient.ProcessMessage() in /Users/earl/planetarium/libplanet/Libplanet.Stun/Stun/TurnClient.cs:line 269
[12:33:03 ERR] An unexpected exception occurred during ProcessMessage(): System.NullReferenceException: Object reference not set to an instance of an object.
   at Libplanet.Stun.TurnClient.ProcessMessage() in /Users/earl/planetarium/libplanet/Libplanet.Stun/Stun/TurnClient.cs:line 275
System.NullReferenceException: Object reference not set to an instance of an object.
   at Libplanet.Stun.TurnClient.ProcessMessage() in /Users/earl/planetarium/libplanet/Libplanet.Stun/Stun/TurnClient.cs:line 275
[12:33:03 ERR] An unexpected exception occurred during ProcessMessage(): System.NullReferenceException: Object reference not set to an instance of an object.
   at Libplanet.Stun.TurnClient.ProcessMessage() in /Users/earl/planetarium/libplanet/Libplanet.Stun/Stun/TurnClient.cs:line 275
System.NullReferenceException: Object reference not set to an instance of an object.
   at Libplanet.Stun.TurnClient.ProcessMessage() in /Users/earl/planetarium/libplanet/Libplanet.Stun/Stun/TurnClient.cs:line 275
```
