### ISSUE TITLE
SwarmTest.BroadcastBlockToReconnectedPeer test fails intermittently

### ISSUE THREAD

**Issue by moreal** [planetarium/libplanet#499]
`LiteDBStoreFixture.Dispose()` cause IOException during unit test on <q>Windows_NETCore_coverage</q> environment.

```
[xUnit.net 00:01:06.18]     Libplanet.Tests.Net.SwarmTest.BroadcastBlockToReconnectedPeer [FAIL]
Failed   Libplanet.Tests.Net.SwarmTest.BroadcastBlockToReconnectedPeer
Error Message:
 System.AggregateException : One or more errors occurred. (The process cannot access the file 'C:\Users\VssAdministrator\AppData\Local\Temp\litedb_ae09bf00-5836-47cf-951b-a6a4bd28e1c1.db' because it is being used by another process.) (Test execution timed out after 60000 milliseconds)
---- System.IO.IOException : The process cannot access the file 'C:\Users\VssAdministrator\AppData\Local\Temp\litedb_ae09bf00-5836-47cf-951b-a6a4bd28e1c1.db' because it is being used by another process.
---- Test execution timed out after 60000 milliseconds
Stack Trace:

----- Inner Stack Trace #1 (System.IO.IOException) -----
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Libplanet.Tests.Store.LiteDBStoreFixture.Dispose() in D:\a\1\s\Libplanet.Tests\Store\LiteDBStoreFixture.cs:line 22
   at Libplanet.Tests.Net.SwarmTest.Dispose() in D:\a\1\s\Libplanet.Tests\Net\SwarmTest.cs:line 123
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 79
----- Inner Stack Trace #2 (Xunit.Sdk.TestTimeoutException) -----
```

**Comment by limebell** [comment]
I think this is the problem of sharing same filestorefixture in swarmA and swarmB in `SwarmTest.BroadcastBlockToReconnectedPeer`.
