### ISSUE TITLE
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 6): Device not configured

### ISSUE THREAD

**Issue by earlbread** [planetarium/libplanet#625]
```
An unexpected exception occurred. try again...
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 6): Device not configured
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at System.Net.Sockets.TcpClient.Connect(String hostname, Int32 port)
   at System.Net.Sockets.TcpClient..ctor(String hostname, Int32 port)
   at Libplanet.Stun.TurnClient.AcceptRelayedStreamAsync(CancellationToken cancellationToken)
   at Libplanet.Net.Swarm`1.BindingProxies(CancellationToken cancellationToken)
```

**Comment by longfin** [comment]
@earlbread Does this error repeat, or only occur once?

**Comment by earlbread** [comment]
This error occurred 7 times total in 12 nodes and occurred 2 times in some nodes.
