### ISSUE TITLE
An unexpected exception occurred during ReceiveMessage(): System.OverflowException

### ISSUE THREAD

**Issue by earlbread** [planetarium/libplanet#626]
```
An unexpected exception occurred during ReceiveMessage(): System.OverflowException: Arithmetic operation resulted in an overflow.
   at Libplanet.Net.Messages.Message.Parse(NetMQMessage raw, Boolean reply)
   at Libplanet.Net.Swarm`1.ReceiveMessage(Object sender, NetMQSocketEventArgs e)
System.OverflowException: Arithmetic operation resulted in an overflow.
   at Libplanet.Net.Messages.Message.Parse(NetMQMessage raw, Boolean reply)
   at Libplanet.Net.Swarm`1.ReceiveMessage(Object sender, NetMQSocketEventArgs e)
```

**Comment by limebell** [comment]
Is there any path to reproduce this?

**Comment by earlbread** [comment]
No, there is no known path to reproduce this.
