### ISSUE TITLE
KademliaProtocol.Peers property sometimes throws InvalidOperationException

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet#673]
Libplanet.Tests.Net.SwarmTest.BroadcastBlockToReconnectedPeer [FAIL]
      System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
      Stack Trace:
           at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
           at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
           at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
           at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
           at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
           at System.Collections.Immutable.ImmutableExtensions.FallbackWrapper`1.get_Count()
           at System.Collections.Immutable.ImmutableList`1.CreateRange(IEnumerable`1 items)
        Libplanet\Net\Protocols\KademliaProtocol.cs(56,0): at Libplanet.Net.Protocols.KademliaProtocol`1.get_Peers()
        Libplanet.Tests\Net\SwarmTest.cs(246,0): at Libplanet.Tests.Net.SwarmTest.<BroadcastBlockToReconnectedPeer>d__14.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        Libplanet.Tests\Net\SwarmTest.cs(266,0): at Libplanet.Tests.Net.SwarmTest.<BroadcastBlockToReconnectedPeer>d__14.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by limebell** [comment]
I guess this happened because `KBucket` is not thread-safe. I'll work on it.

**Comment by longfin** [comment]
@limebell Is it still a valid issue?
