### ISSUE TITLE
Need more appropriate exception than InvalidGenesisBlockException

### ISSUE THREAD

**Issue by earlbread** [planetarium/libplanet#952]
```
[02:03:26 DBG] Branch point is #51512 077efb16412a85503c3e9816945d5c746980c76be7ba8a8218531b9e38000000.
[02:03:26 DBG] Deleting chainID: 8a2a7e0f-1a5c-43f2-87e5-178a485d61bd.
[02:03:26 ERR] Unexpected exception occurred during ProcessFillblock: Libplanet.Blocks.InvalidGenesisBlockException: Since the genesis block is fixed to b1a4948888b02bfec2b494aeeab7ef8a3d09c57f050193a7eb296937947cc642 protocol-wise, the blockchain which does not share any mutual block is not acceptable.
   at Libplanet.Net.Swarm`1.FillBlocksAsync(BoundPeer peer, BlockChain`1 blockChain, Nullable`1 stop, IProgress`1 progress, Int64 totalBlockCount, Int64 receivedBlockCount, Boolean evaluateActions, CancellationToken cancellationToken)
   at Libplanet.Net.Swarm`1.SyncPreviousBlocksAsync(BlockChain`1 blockChain, BoundPeer peer, Nullable`1 stop, IProgress`1 progress, Int64 totalBlockCount, Boolean evaluateActions, CancellationToken cancellationToken)
   at Libplanet.Net.Swarm`1.ProcessFillblock(CancellationToken cancellationToken)
```
This is not an exception caused because the genesis block is invalid.

**Comment by limebell** [comment]
Can you please describe the situation of this case in detail?
